site_name: AgenaIndicator Dokumentation (Deutsch)
docs_dir: sources
theme: readthedocs
site_favicon: favicon.ico
extra_css: [custom.css]
use_directory_urls: true
repo_url: https://github.com/AgenaTrader/AgenaIndicator-documentation-de
edit_uri: edit/master/sources/
site_url: https://agenatrader.github.io/AgenaIndicator-documentation-de/index.html
strict: true
google_analytics: ['UA-74646070-1', 'agenatrader.github.io']
pages:
    - 'Lets start': 'index.md'
    - 'Daten': 'daten.md'
    - 'Indikatoren & Oszillatoren': 'indikatoren_und_oszillatoren.md'
